### ISSUE TITLE
High-Performance order storage

### ISSUE THREAD

**Issue by leventkaramanoglu** [ChillCode/simple-menu-order-column#1]
This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated.

**Comment by ChillCode** [comment]
Hi @leventkaramanoglu 

Did not even know about this feature, and Woo did not flag it as not compatible, I've two other plugins that are not and they are3 listed.

Will try to add support on next release.

Thanks for the input.

**Comment by leventkaramanoglu** [comment]
Congratulations on the plugin. It helps me a lot and I like to use it. There is only one problem, it shows woo as incompatible. But it still continues to work. 
I wish you success.

**Comment by ChillCode** [comment]
After digging now I know why this false positive appears since on my Install did not appear.

The readme contains the text **WC tested up to**, but I removed it on my last commit since it's unnecessary and on my end I did not have that message, but previous versions are marked as incompatible.

Will try to upgrade this morning.

Thanks for your kind words!
